/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthenticatedTracksRouteImport } from './routes/_authenticated/tracks'
import { Route as AuthenticatedTachesRouteImport } from './routes/_authenticated/taches'
import { Route as AuthenticatedSubventionsRouteImport } from './routes/_authenticated/subventions'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedFeesRouteImport } from './routes/_authenticated/fees'
import { Route as AuthenticatedFacturesRouteImport } from './routes/_authenticated/factures'
import { Route as AuthenticatedCalendrierRouteImport } from './routes/_authenticated/calendrier'
import { Route as AuthenticatedCachetsRouteImport } from './routes/_authenticated/cachets'
import { Route as ApiPublicHooksScrapeNewsRouteImport } from './routes/api/public/hooks/scrape-news'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTracksRoute = AuthenticatedTracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTachesRoute = AuthenticatedTachesRouteImport.update({
  id: '/taches',
  path: '/taches',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubventionsRoute =
  AuthenticatedSubventionsRouteImport.update({
    id: '/subventions',
    path: '/subventions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeesRoute = AuthenticatedFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFacturesRoute = AuthenticatedFacturesRouteImport.update({
  id: '/factures',
  path: '/factures',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendrierRoute = AuthenticatedCalendrierRouteImport.update({
  id: '/calendrier',
  path: '/calendrier',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCachetsRoute = AuthenticatedCachetsRouteImport.update({
  id: '/cachets',
  path: '/cachets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHooksScrapeNewsRoute =
  ApiPublicHooksScrapeNewsRouteImport.update({
    id: '/api/public/hooks/scrape-news',
    path: '/api/public/hooks/scrape-news',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/cachets': typeof AuthenticatedCachetsRoute
  '/calendrier': typeof AuthenticatedCalendrierRoute
  '/factures': typeof AuthenticatedFacturesRoute
  '/fees': typeof AuthenticatedFeesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/subventions': typeof AuthenticatedSubventionsRoute
  '/taches': typeof AuthenticatedTachesRoute
  '/tracks': typeof AuthenticatedTracksRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/api/public/hooks/scrape-news': typeof ApiPublicHooksScrapeNewsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/cachets': typeof AuthenticatedCachetsRoute
  '/calendrier': typeof AuthenticatedCalendrierRoute
  '/factures': typeof AuthenticatedFacturesRoute
  '/fees': typeof AuthenticatedFeesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/subventions': typeof AuthenticatedSubventionsRoute
  '/taches': typeof AuthenticatedTachesRoute
  '/tracks': typeof AuthenticatedTracksRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/api/public/hooks/scrape-news': typeof ApiPublicHooksScrapeNewsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_authenticated/cachets': typeof AuthenticatedCachetsRoute
  '/_authenticated/calendrier': typeof AuthenticatedCalendrierRoute
  '/_authenticated/factures': typeof AuthenticatedFacturesRoute
  '/_authenticated/fees': typeof AuthenticatedFeesRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/subventions': typeof AuthenticatedSubventionsRoute
  '/_authenticated/taches': typeof AuthenticatedTachesRoute
  '/_authenticated/tracks': typeof AuthenticatedTracksRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/api/public/hooks/scrape-news': typeof ApiPublicHooksScrapeNewsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/unsubscribe'
    | '/cachets'
    | '/calendrier'
    | '/factures'
    | '/fees'
    | '/onboarding'
    | '/subventions'
    | '/taches'
    | '/tracks'
    | '/email/unsubscribe'
    | '/api/public/hooks/scrape-news'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/unsubscribe'
    | '/cachets'
    | '/calendrier'
    | '/factures'
    | '/fees'
    | '/onboarding'
    | '/subventions'
    | '/taches'
    | '/tracks'
    | '/email/unsubscribe'
    | '/api/public/hooks/scrape-news'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/unsubscribe'
    | '/_authenticated/cachets'
    | '/_authenticated/calendrier'
    | '/_authenticated/factures'
    | '/_authenticated/fees'
    | '/_authenticated/onboarding'
    | '/_authenticated/subventions'
    | '/_authenticated/taches'
    | '/_authenticated/tracks'
    | '/email/unsubscribe'
    | '/api/public/hooks/scrape-news'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  ApiPublicHooksScrapeNewsRoute: typeof ApiPublicHooksScrapeNewsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tracks': {
      id: '/_authenticated/tracks'
      path: '/tracks'
      fullPath: '/tracks'
      preLoaderRoute: typeof AuthenticatedTracksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/taches': {
      id: '/_authenticated/taches'
      path: '/taches'
      fullPath: '/taches'
      preLoaderRoute: typeof AuthenticatedTachesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subventions': {
      id: '/_authenticated/subventions'
      path: '/subventions'
      fullPath: '/subventions'
      preLoaderRoute: typeof AuthenticatedSubventionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fees': {
      id: '/_authenticated/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof AuthenticatedFeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/factures': {
      id: '/_authenticated/factures'
      path: '/factures'
      fullPath: '/factures'
      preLoaderRoute: typeof AuthenticatedFacturesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendrier': {
      id: '/_authenticated/calendrier'
      path: '/calendrier'
      fullPath: '/calendrier'
      preLoaderRoute: typeof AuthenticatedCalendrierRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cachets': {
      id: '/_authenticated/cachets'
      path: '/cachets'
      fullPath: '/cachets'
      preLoaderRoute: typeof AuthenticatedCachetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/scrape-news': {
      id: '/api/public/hooks/scrape-news'
      path: '/api/public/hooks/scrape-news'
      fullPath: '/api/public/hooks/scrape-news'
      preLoaderRoute: typeof ApiPublicHooksScrapeNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCachetsRoute: typeof AuthenticatedCachetsRoute
  AuthenticatedCalendrierRoute: typeof AuthenticatedCalendrierRoute
  AuthenticatedFacturesRoute: typeof AuthenticatedFacturesRoute
  AuthenticatedFeesRoute: typeof AuthenticatedFeesRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSubventionsRoute: typeof AuthenticatedSubventionsRoute
  AuthenticatedTachesRoute: typeof AuthenticatedTachesRoute
  AuthenticatedTracksRoute: typeof AuthenticatedTracksRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCachetsRoute: AuthenticatedCachetsRoute,
  AuthenticatedCalendrierRoute: AuthenticatedCalendrierRoute,
  AuthenticatedFacturesRoute: AuthenticatedFacturesRoute,
  AuthenticatedFeesRoute: AuthenticatedFeesRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSubventionsRoute: AuthenticatedSubventionsRoute,
  AuthenticatedTachesRoute: AuthenticatedTachesRoute,
  AuthenticatedTracksRoute: AuthenticatedTracksRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  ApiPublicHooksScrapeNewsRoute: ApiPublicHooksScrapeNewsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
