/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthenticatedTracksRouteImport } from './routes/_authenticated/tracks'
import { Route as AuthenticatedTachesRouteImport } from './routes/_authenticated/taches'
import { Route as AuthenticatedSubventionsRouteImport } from './routes/_authenticated/subventions'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedInvitationsRouteImport } from './routes/_authenticated/invitations'
import { Route as AuthenticatedCalendrierRouteImport } from './routes/_authenticated/calendrier'
import { Route as AuthenticatedFinanceIndexRouteImport } from './routes/_authenticated/finance/index'
import { Route as AuthenticatedFinanceFeesRouteImport } from './routes/_authenticated/finance/fees'
import { Route as AuthenticatedFinanceCachetsRouteImport } from './routes/_authenticated/finance/cachets'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTracksRoute = AuthenticatedTracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTachesRoute = AuthenticatedTachesRouteImport.update({
  id: '/taches',
  path: '/taches',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubventionsRoute =
  AuthenticatedSubventionsRouteImport.update({
    id: '/subventions',
    path: '/subventions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvitationsRoute =
  AuthenticatedInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCalendrierRoute = AuthenticatedCalendrierRouteImport.update({
  id: '/calendrier',
  path: '/calendrier',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceIndexRoute =
  AuthenticatedFinanceIndexRouteImport.update({
    id: '/finance/',
    path: '/finance/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceFeesRoute =
  AuthenticatedFinanceFeesRouteImport.update({
    id: '/finance/fees',
    path: '/finance/fees',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceCachetsRoute =
  AuthenticatedFinanceCachetsRouteImport.update({
    id: '/finance/cachets',
    path: '/finance/cachets',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/calendrier': typeof AuthenticatedCalendrierRoute
  '/invitations': typeof AuthenticatedInvitationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/subventions': typeof AuthenticatedSubventionsRoute
  '/taches': typeof AuthenticatedTachesRoute
  '/tracks': typeof AuthenticatedTracksRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/finance/cachets': typeof AuthenticatedFinanceCachetsRoute
  '/finance/fees': typeof AuthenticatedFinanceFeesRoute
  '/finance/': typeof AuthenticatedFinanceIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/calendrier': typeof AuthenticatedCalendrierRoute
  '/invitations': typeof AuthenticatedInvitationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/subventions': typeof AuthenticatedSubventionsRoute
  '/taches': typeof AuthenticatedTachesRoute
  '/tracks': typeof AuthenticatedTracksRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/': typeof AuthenticatedIndexRoute
  '/finance/cachets': typeof AuthenticatedFinanceCachetsRoute
  '/finance/fees': typeof AuthenticatedFinanceFeesRoute
  '/finance': typeof AuthenticatedFinanceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_authenticated/calendrier': typeof AuthenticatedCalendrierRoute
  '/_authenticated/invitations': typeof AuthenticatedInvitationsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/subventions': typeof AuthenticatedSubventionsRoute
  '/_authenticated/taches': typeof AuthenticatedTachesRoute
  '/_authenticated/tracks': typeof AuthenticatedTracksRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/finance/cachets': typeof AuthenticatedFinanceCachetsRoute
  '/_authenticated/finance/fees': typeof AuthenticatedFinanceFeesRoute
  '/_authenticated/finance/': typeof AuthenticatedFinanceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/unsubscribe'
    | '/calendrier'
    | '/invitations'
    | '/onboarding'
    | '/subventions'
    | '/taches'
    | '/tracks'
    | '/email/unsubscribe'
    | '/finance/cachets'
    | '/finance/fees'
    | '/finance/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/unsubscribe'
    | '/calendrier'
    | '/invitations'
    | '/onboarding'
    | '/subventions'
    | '/taches'
    | '/tracks'
    | '/email/unsubscribe'
    | '/'
    | '/finance/cachets'
    | '/finance/fees'
    | '/finance'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/unsubscribe'
    | '/_authenticated/calendrier'
    | '/_authenticated/invitations'
    | '/_authenticated/onboarding'
    | '/_authenticated/subventions'
    | '/_authenticated/taches'
    | '/_authenticated/tracks'
    | '/email/unsubscribe'
    | '/_authenticated/'
    | '/_authenticated/finance/cachets'
    | '/_authenticated/finance/fees'
    | '/_authenticated/finance/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tracks': {
      id: '/_authenticated/tracks'
      path: '/tracks'
      fullPath: '/tracks'
      preLoaderRoute: typeof AuthenticatedTracksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/taches': {
      id: '/_authenticated/taches'
      path: '/taches'
      fullPath: '/taches'
      preLoaderRoute: typeof AuthenticatedTachesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subventions': {
      id: '/_authenticated/subventions'
      path: '/subventions'
      fullPath: '/subventions'
      preLoaderRoute: typeof AuthenticatedSubventionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invitations': {
      id: '/_authenticated/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof AuthenticatedInvitationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendrier': {
      id: '/_authenticated/calendrier'
      path: '/calendrier'
      fullPath: '/calendrier'
      preLoaderRoute: typeof AuthenticatedCalendrierRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/': {
      id: '/_authenticated/finance/'
      path: '/finance'
      fullPath: '/finance/'
      preLoaderRoute: typeof AuthenticatedFinanceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/fees': {
      id: '/_authenticated/finance/fees'
      path: '/finance/fees'
      fullPath: '/finance/fees'
      preLoaderRoute: typeof AuthenticatedFinanceFeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/cachets': {
      id: '/_authenticated/finance/cachets'
      path: '/finance/cachets'
      fullPath: '/finance/cachets'
      preLoaderRoute: typeof AuthenticatedFinanceCachetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCalendrierRoute: typeof AuthenticatedCalendrierRoute
  AuthenticatedInvitationsRoute: typeof AuthenticatedInvitationsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSubventionsRoute: typeof AuthenticatedSubventionsRoute
  AuthenticatedTachesRoute: typeof AuthenticatedTachesRoute
  AuthenticatedTracksRoute: typeof AuthenticatedTracksRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedFinanceCachetsRoute: typeof AuthenticatedFinanceCachetsRoute
  AuthenticatedFinanceFeesRoute: typeof AuthenticatedFinanceFeesRoute
  AuthenticatedFinanceIndexRoute: typeof AuthenticatedFinanceIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCalendrierRoute: AuthenticatedCalendrierRoute,
  AuthenticatedInvitationsRoute: AuthenticatedInvitationsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSubventionsRoute: AuthenticatedSubventionsRoute,
  AuthenticatedTachesRoute: AuthenticatedTachesRoute,
  AuthenticatedTracksRoute: AuthenticatedTracksRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedFinanceCachetsRoute: AuthenticatedFinanceCachetsRoute,
  AuthenticatedFinanceFeesRoute: AuthenticatedFinanceFeesRoute,
  AuthenticatedFinanceIndexRoute: AuthenticatedFinanceIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
